name: Update TODO backlinks
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3
    - name: todo-backlinks
      uses: j2kun/todo-backlinks@c3745671fa215840545336571fc397ac2948d66a # pin@v0.0.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
